name: Push To DockerHub

on:
  pull_request:
    types: [ closed ]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout The Repo
        uses: actions/checkout@v2
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: shehuawwal/nodejs-app

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and Push Image
        run: |
          docker login --username=$DOCKER_USER --password=$DOCKER_PASSWORD
          docker build -t shehuawwal/nodejs-app:latest .
          docker push shehuawwal/nodejs-app:latest 

      
      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}