name: Actions Workfw

on: [push]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Actions
        id: greet
        uses: hello-world-javascript-action@v1
        with:
          who-to-greet: 'Lutz'

      - name: Log Greeting Time
        run: echo "{{ steps.greet.outputs.time }}"