name: Shell Commands

on:
  - push
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    
    steps:
      - name: echo a string
        run: echo "Hello Africa"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python Command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-shell-on-windows:
    runs-on: windows-latest

    steps:
      - name: Get Directory
        run: Get-Location
      - name: Directory Bash
        run: pwd && echo $(ps -p $$)
        shell: bash
